def updateOutTime(layerDict, currentStep):

	''' 
	Update the time instant in which the neurons have generated a spike.

	INPUT PARAMETERS: 

		1) layerdict: dictionary containing the parameters of the layer,
		in particular:

			a) t_out: NumPy array containing the instants of the
			last spike generated by each neuron in the layer.

			b) outEvents: boolean numpy array containing the spikes
			generated by the layer.

		2) currentStep: current value of the network training loop
		index. 

	'''

	layerDict["t_out"][layerDict["outEvents"]] = currentStep - 1






def updateInOutMasks(layerDict, inEvents):

	''' Update the input and output masks.

	INPUT: 
		1) layerDict: dictionary containing the parameters of all the
		neurons inside the layer. 

		2) inEvents: boolean NumPy array containing the input of the
		current layer corresponding to the current step.
	'''

	# Update the mask of neurons that have already been active
	updateMask(layerDict, "outMask", layerDict["outEvents"])

	# Update the mask of inputs that have already been active
	updateMask(layerDict, "inMask", inEvents)





