#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Nov 03 17:58:01 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto c7b78bae3a3f472ab54ba66ed72a5b59 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot add_sub_tb_behav xil_defaultlib.add_sub_tb -log elaborate.log"
xelab -wto c7b78bae3a3f472ab54ba66ed72a5b59 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot add_sub_tb_behav xil_defaultlib.add_sub_tb -log elaborate.log

