name: spiker
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pip
  - pip:
      - torch      
      - torchvision
      - torchaudio
      - snntorch
      - tabulate
      - tonic
      - ./spiker
