#!/Users/alessio/anaconda3/bin/python3

# Function that models the behaviour of a fully connected spiking neural network.
#
# INPUT PARAMETERS:
#
# 	1) inEvents: NumPy array which contains the input spikes.
#
# 	2) layersList: list of lists of dictionaries containing the parameters
# 	   of the neurons.
#
# 	3) dt_tau: numerical value of delta_t/tau. See the function "neuron" for
# 	   more details.
#
# 	4) outEvents: preallocated bidimensional array containing the outputs of
# 	   each layer. 
#
# The function loops over all the layers and updates the membrane potential and the
# output events generated by the various neurons.

from layer import layer

def snn(inEvents, layersList, dt_tau, outEvents):


	# Update the first layer with the input events
	layer(inEvents, layersList[0], dt_tau, outEvents[0], len(layersList[0]))

	# Loop over all the other layers in the network updating them
	# using the output of the previous layer as an input
	for i in range(1, len(layersList)):

		# Update the layer
		layer(outEvents[i-1], layersList[i], dt_tau, outEvents[i], 
			len(layersList[i]))
