#!/Users/alessio/anaconda3/bin/python3

# Function that models the behaviour of a fully connected spiking neural network.
#
# INPUT PARAMETERS:
#
# 	1) inEvents: NumPy array which contains the input spikes.
#
# 	2) layersList: list of lists of dictionaries containing the parameters
# 	   of the neurons.
#
# 	3) dt_tau: numerical value of delta_t/tau. See the function "neuron" for
# 	   more details.
#
# 	4) outEvents_list: list of arrays containing the outputs of each layer. 
#
# The function loops over all the layers and updates the membrane potential and the
# output events generated by the various neurons.

from layer import layer

def snn(inEvents, networkDictList, dt_tau, outEvents_list, layersList):

	# Update the first layer with the input events
	layer(inEvents, networkDictList[0], dt_tau, outEvents_list[0], layersList[1])

	# Loop over all the other layers in the network updating them
	# using the output of the previous layer as an input
	for i in range(1, len(layersList)-1):

		# Update the layer
		layer(outEvents_list[i-1], networkDictList[i], dt_tau, outEvents_list[i], 
			layersList[i+1])
